import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false;
import StoreProvider from "./StoreProvider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import StyledComponentsRegistry from "@/lib/registry";

import DiscountFirst from "@/components/DiscountFirst";
import Navbar from "@/components/Header/Navbar";
import ThemeWrapper from "@/themes/ThemeWrapper";
import { GlobalStyles } from "@/styles/ComponentStyle";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout(props) {
    const { children, params: { locale } } = props;
    const messages = await getMessages({ locale });
    return (
        <html lang={locale}>
            <body>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <StoreProvider>
                        <ThemeWrapper >
                        <GlobalStyles />
                            <StyledComponentsRegistry>
                                <DiscountFirst />
                                <Navbar />
                                {children}
                            </StyledComponentsRegistry>
                        </ThemeWrapper>
                    </StoreProvider>
                </NextIntlClientProvider>
                <script
                    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                    crossOrigin="anonymous"
                    async
                ></script>
            </body>
        </html>
    );
}

